apiVersion: v2
name: java-microservices
description: Helm chart for deploying Java microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: Tejas Targhale
    email: tejastarghale47@gmail.com